### ISSUE TITLE
first review

### ISSUE THREAD

**Issue by aizjicod** [Fourteen98/Pokemon#21]
- [project link](https://github.com/Fourteen98/Pokemone/projects/1)
- there are 2 people on the project.

**Comment by sja-thedude** [comment]
## Required Changes ♻️

Hi @aizjicod & @Fourteen98, This is @sja-thedude your code reviewer.

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![768070f3-bc9a-4aba-b8bc-25793e00ea1e_text](https://user-images.githubusercontent.com/70269507/159483175-2f61461d-b352-4cb4-98f8-b173e05ab5ff.gif)

## Required 
- [x] Kindly assign members equally for all the cards by adding member in assignees with the example shown below:

https://user-images.githubusercontent.com/70269507/180878322-3fbbee5d-e740-4eb5-9a56-d17b74a0cd91.mov

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rloterh** [comment]
## Status: Approved :heavy_check_mark:

Hi Team,  

Your project is complete! 🍾🚢 Congratulations!  🎉💯🌟 

## Highlights 👍
- Fair distribution of tasks
- Good descriptive board title and description of task

<br>
Keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
